---
root: true
parser: '@typescript-eslint/parser'
parserOptions:
  project: './tsconfig.dev.json'

plugins:
  - header
  - '@typescript-eslint'

# https://eslint.org/docs/user-guide/configuring#specifying-environments
env:
  node: true
  mocha: true

extends:
  - './src/b12/eslint-config/typescript'
  - 'plugin:@typescript-eslint/recommended'
  - 'plugin:@typescript-eslint/recommended-requiring-type-checking'

# https://github.com/Stuk/eslint-plugin-header
rules:
 header/header: [2, 'line', [
    '//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////',
    '',
    '  Copyright (C) 2008 Quantron Systems LLC.',
    '  All Rights Reserved.',
    '',
    '  This file is part of the Private project.',
    '  For conditions of distribution and use,',
    '  please contact sales@quantron-systems.com',
    '',
    '//////////////////////////////////////////////////////////////////////////////////////////////////////////////////////'
  ]]

overrides:
  - files: '*Test.[tj]s'
    rules:
      require-atomic-updates: 0
  - files: ['*.ts', '*.tsx']
    rules:
      no-undef: 0
  - files: ['*.js', '*.jsx']
    rules:
      '@typescript-eslint/no-unsafe-assignment': 0
      '@typescript-eslint/no-unsafe-member-access': 0
      '@typescript-eslint/no-unsafe-return': 0
      '@typescript-eslint/restrict-template-expressions': 0
      '@typescript-eslint/no-unsafe-call': 0
