test:
  stage: test
  before_script:
    - docker volume create nodemodules
    - docker-compose up --build -d
  script:
    - mkdir logs
    - docker-compose exec -T app sh -c '/wait'
    - docker-compose exec -T app npm run lint
    - docker-compose exec -T app npm run typecheck
    - docker-compose exec -T app npm run spellcheck
    - docker-compose exec -T app npm run test
  after_script:
    - docker-compose -f ./docker-compose.yml down -v
    - docker volume rm -f nodemodules
  artifacts:
    when: always
    paths:
      - logs/
    expire_in: 1 week
  tags:
    - ubuntu
