version: "3.4"

x-mongo-base:
  &mongo-base
  image: mongo:4.4
  entrypoint: [ "/usr/bin/mongod", "--bind_ip_all", "--replSet", "fango-mongo-set" ]

services:
  fango-mongo-rs0:
    << : *mongo-base
    container_name: fango-mongo-rs0
    healthcheck:
        test: test $$(echo "rs.initiate().ok || rs.status().ok" | mongo --quiet) -eq 1 # initiates replSet
        interval: 10s
        start_period: 30s
    ports:
      - 27017:27017

  elastic:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.9.0
    container_name: fango-elastic
    ports:
      - 9200:9200
    environment:
      - discovery.type=single-node
      - cluster.name=docker-cluster
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - cluster.routing.allocation.disk.threshold_enabled=false

  app:
    container_name: app
    build:
      context: .
      dockerfile: ./docker/development.dockerfile
    environment:
      WAIT_HOSTS: fango-mongo-rs0:27017, fango-elastic:9200
    volumes:
      - ./config.ci.json:/usr/src/app/config.local.json
    tty: true
    stdin_open: true
